### ISSUE TITLE
Toggle key not working since Firefox 37

### ISSUE THREAD

**Issue by tdido** [greizgh/Phashword#11]
I've tried reinstalling a few times, changing the assigned key shortcut, but the only way of disabling for me right now is to do it by the icon or by right-clicking on the page.

**Comment by greizgh** [comment]
Thanks for reporting your issue.
Although it should not change anything, please make sure you are using latest version of the extension (1.5.1).
If you are using an extension like *vimperator* or *pentadactyl*, be sure not to use escape key as phashword toggle key, as there might be conflicts.
After some testing, it appears that changing the toggle key in preferences is not taken into account before a firefox restart (I'll open another issue for that).
Could you try to restart firefox after changing the toggle key?

**Comment by tdido** [comment]
Thanks for your quick reply.

I restarted Firefox and indeed I can now toggle with a different key. Now I'll try to figure out what's going with the escape key

Thanks!
