### ISSUE TITLE
QR code representation of private key

### ISSUE THREAD

**Issue by PacoBell** [greizgh/Phashword#15]
This is a minor feature request, but it'd be great if the private key could be shown as a QR code for potentially easier importing into mobile devices. I don't trust that information to travel over any network, even in encrypted form (quantum-pocalpyse, yo) and typing it manually is extremely error prone. Thanks!

**Comment by greizgh** [comment]
Thanks for this suggestion, it makes sense to add this feature.
Expect to see it in next release.
