### ISSUE TITLE
Remember password parameters per tag

### ISSUE THREAD

**Issue by PacoBell** [greizgh/Phashword#16]
I believe this is something Twik does. It definitely solves the usability issue users have with having to remember the idiosyncrasies of each site's complexity requirements (although at the slightly increased risk of leaking information to an attacker who compromises your endpoint).

**Comment by greizgh** [comment]
Indeed, Twik does handle per site password. This is something phashword should do.
Thanks for bringing it up in my todo list ;)

**Comment by greizgh** [comment]
Starting with release 1.5.9, password type and length are stored per website.
