### ISSUE TITLE
Websites can receive master password

### ISSUE THREAD

**Issue by L-Henke** [greizgh/Phashword#17]
I think that Phashword has a massive design flaw, since websites can read the master password while your are typing. 

An example for this is the Github password change form. Every entered character is directly posted to ```https://github.com/signup_check/password``` as you can easily see in the developer console of Firefox. Although nobody can do anything without having your private key, it is _extremely_ uncomfortable that every website can receive the master key if they want to.

**Comment by greizgh** [comment]
Well, thanks for noticing this behaviour.
As you said, this is not critical as your private key is kept safe, but this is definitely not an optimal situation.
As a temporary workaround, you can use the pop-up menu and copy/paste the password.

The solution I envision is to bypass form feedback by creating a custom field replacing the one used in the page. The idea here is to make the master password input happen in a _private_ field created by phashword then switch with the _native_ field and insert the hash there.

**Comment by L-Henke** [comment]
> The solution I envision is to bypass form feedback by creating a custom field replacing the one used in the page.

I had something similar in my mind, but no idea if the Firefox add-on architecture allows such a thing.

**Comment by mafrailea** [comment]
And, while this is fixed, it would be great if Phashword could be disabled by default on all sites, so you have to enable it for the sites that you generate a password.

Maybe not as the default behaviour, but it would be nice if there existed an option on the settings to disable Phashword for all sites by default.

Thanks for your great work!

**Comment by greizgh** [comment]
Hi @mafrailea. There is already an option to change the default state of Phashword (enabled/disable). Go to add-on preferences and uncheck "default status" to disable Phashword globally. You will still be able to enable it per website though the popin menu.

**Comment by mafrailea** [comment]
My bad! I didn't notice there were additional options in the addon settings. So maybe I can suggest to consolidate all options in the same place. :)

But, no matter where the option is located, it's great that it exists and it's more than enough for me!

So, @greizgh, thanks for your work and for such a quick reply! :+1:

**Comment by greizgh** [comment]
No problem @mafrailea! Indeed it would be nice to have all options at the same place. To be honest, I'm not satisfied with current settings page.

To add more on this issue: I'm not completely sure on how to circumvent master password leak. My initial thought was to create a temporary password field but this is not optimal.
Let's think as a paranoid: although it would prevent password leak on pages that check password on every keypress, a malicious script would still be able to log all pressed keys (a js keylogger).
The only way I see to prevent the password to appear on the page would be to ask the user for it _outside_ of the page.

**Comment by mafrailea** [comment]
Hum, I think something similar to an InputBox (if it could be forced to use a password entry field) would help as *I think* that, while a modal dialog is shown, Javascript is not available.

Then, with an script, you can hash the master key into the site password and feed it to the password box.

It could be a very nice solution as you could show the password InputBox whenever the user focus the password field, but the main problem here is that I think there's no way to use a password field on an InputBox.

Hope it can be helpful or, at least, route you to other different solutions, @greizgh.

**Comment by mafrailea** [comment]
@greizgh, I checked my previous idea and Firefox shows a Javascript dialog inside the site window object instead of a browser dialog, so I think it isn't a valid solution.

But I had another idea. When the user presses the plugin button, you show a configuration dialog under the browser object (and not under the current site object).

So I don't know if it's possible, but maybe when the user focus the password field you can show an addon dialog under the browser object where the user enters the master password and, then, you feed the hashed password to the password field.

**Comment by greizgh** [comment]
You can now enable external prompt in settings page: this will show a popup asking for your master password. This is an opt-in behaviour as it may hinder usability.
The prompt is handled in a different process than the current page, so it should prevent any leaks.
