### ISSUE TITLE
Not fully compatible with Twik

### ISSUE THREAD

**Issue by L-Henke** [greizgh/Phashword#18]
Special characters in the master key are resulting in different passwords than in Twik.

e.g. German [umlauts](https://en.wikipedia.org/wiki/Umlaut_%28linguistics%29) like ä ö ü, but also other characters like the € symbol are leading to different passwords.

**Comment by L-Henke** [comment]
This seems to work now. But it might change the generated passwords for some users, so maybe an notification would be good.

**Comment by greizgh** [comment]
Good catch. It's only late in the night that retrocompatibility came to my mind. I will update the release and the addon page on mozilla AMO.
