### ISSUE TITLE
Default Status

### ISSUE THREAD

**Issue by JeremyWW** [greizgh/Phashword#19]
Tried this a few times but unchecking the default status option makes no difference. Phashword is always enabled regardless.

**Comment by greizgh** [comment]
It might come from a stored site profile: please make sure to try on a new site and/or remove stored profile (you can do it form the settings page)

**Comment by JeremyWW** [comment]
OK, thanks. I understand what's happening now. Rather than start a new 'Issue', can I ask what use you think 'Profiles' are? I can see that Phashword and Twik both 'remember' site settings so different profiles are not required for differing site password requirements. The other thing that both Phashword and Twik need is the ability to export / import the site 'list' with the stored password settings for backup purposes as well as moving a site list to Twik on a mobile and vica versa. Is that something that's possible?

**Comment by greizgh** [comment]
Hi!
Profiles are kind of presets, you can use them to separate your identities (work/personal).
Profile import/export is possible, although we need to agree on a common format to exchange data between twik and phashword.

**Comment by JeremyWW** [comment]
Just replied to the Enhancement... So, yes, are you able to agree that with the Twik dev?

**Comment by greizgh** [comment]
We will certainly find something. Closing this issue as it is resolved. Reopen it in case it's not.
