### ISSUE TITLE
Can't toggle phashword in iframe

### ISSUE THREAD

**Issue by JeremyWW** [greizgh/Phashword#20]
Hi,

Discovered a potential challenge for you...

On sites where you make a purchase with a Visa credit card you'll be redirected at the end of the process to an online payment system, such as SagePay. On that page the 'Verified by Visa' panel will appear which requires, for example, the first, fifth, and tenth letters of your password. Phashword insists on 'colouring' those very small fields, requesting the Master Key, which of course will never work as it isn't a complete password but random letters / numbers in small separate fields. It isn't possible to disable Phashword for this either as the Verified by Visa panel is 'inserted' into the host webpage, so disabling Phashword only disables it for that 'host' page and has no effect on the Verified by Visa panel which simply isn't recognised / picked up by Phashword. What you have to do then is disable Phashword for each of those tiny fields before you can go any further, which is a pain.

Is there any way of dealing with this?

Thanks.

**Comment by greizgh** [comment]
This is probably due to iframe inclusion.
Can you toggle phashword for the whole iframe through contextual menu (right-click)?

**Comment by JeremyWW** [comment]
Of course, iframe... makes sense. I'm almost certain I tried that. Can't be 100% so I'll try that next time and report back here.

**Comment by JeremyWW** [comment]
Just tried toggling Phashword for the iFrame - it doesn't work. It's only 'seeing' the main page address.

**Comment by greizgh** [comment]
OK, I'll see what I can do then
