### ISSUE TITLE
Hide white bar on bottom of page

### ISSUE THREAD

**Issue by paxy97** [greizgh/Phashword#24]
On some pages Phashword adds a visible input field on the bottom of the body.

https://i.imgur.com/Ya7cWqz.png

Is there a way to hide it without impacting the functionality? It doesn't have an id or class, so theres no way to get rid of it with css

**Comment by greizgh** [comment]
Thanks for reporting this.
Could you provide some links where I can reproduce the problem?

**Comment by paxy97** [comment]
[I put up my own example](http://xor-hydrogen.me:8080/) where I noticed it, since it's white. It's just the defualt vue vuetify boilerplate code if you want to test it yourself.

I also saw it on [this site](http://www.aerospace.org/cords/reentry-predictions/tiangong-1-reentry/) for example, though it's not white, only add spacing below the footer.

I seems to occur on most react applications I've made myself, tohugh I can't link you to one.
