### ISSUE TITLE
Settings are reset and plugin stops working on firefox 57

### ISSUE THREAD

**Issue by paxy97** [greizgh/Phashword#25]
I use ff developer edition (v57), and every time I restart ff I have to reinstall phashword, otherwise it's unusable. I can't create profiles (and the existing one get deleted). I can't even change the toggle key and default state.

I'll be happy to provide any additional information, just tell me what you need.

**Comment by greizgh** [comment]
Thanks for your report.
This is a bug I've been facing in ff dev edition for some time but I hadn't had time to dig into it.
Something may have changed in the way firefox stores objects in its local storage.

**Comment by greizgh** [comment]
I just published a pre-release which should fix this issue, see [release 2.2.0rc1](https://github.com/greizgh/Phashword/releases/tag/v2.2.0rc1).
You can install the release through mozilla's addon page: https://addons.mozilla.org/fr/firefox/addon/phashword/versions/beta?page=1#version-2.2.0rc1

Please note that it is supposed to migrate data from a firefox version <57. If you do not have access to your data from a firefox stable profile I'm afraid your data might be corrupted (that explains why the addon was stuck in an unusable state).

Do not hesitate to report any weird behavior related to this pre release.

**Comment by paxy97** [comment]
Wait, I don't understand what you mean by "It's supposed to migrate data fron a firefox version <57". Do you mean that I should downgrade ff dev, install the new version of phashword and then update ff?

What I tried was removing phashword and then installing the new version, but it didn't work

**Comment by greizgh** [comment]
Downgrade is not mandatory: uninstalling the addon and reinstalling v2.2.0 should be enough to have a working addon.
The idea is to gracefully handle the transition to ff57 and avoid the corruption you experienced. That's why v2.2.0 will switch backend and correctly serialize the addon state. That means people following stable release of firefox won't loose their data.

**Comment by paxy97** [comment]
After uninstalling, and reinstalling I couldn't even set it up on the first start (i used to be able to do that before). I tried copying the storage.js file from ff 55 with the current phashword release into the dev profle, but that didn't work either :/

**Comment by greizgh** [comment]
Ho I see, the corrupted state might have been stored in sync storage.
In rc3 I check for state corruption before loading the addon, this should do the trick.

**Comment by paxy97** [comment]
Fixed now, thank you very much <3
