### ISSUE TITLE
Migration to sync backend (2.2.0) fails in Firefox 52 ESR

### ISSUE THREAD

**Issue by mario98** [greizgh/Phashword#26]
In Firefox 52 ESR, the pref "webextensions.storage.sync.enabled" is set to "false" by default (for some reason...) therefore the sync backend cannot be accessed by addons. So when version 2.2.0 is installed, you completely loose your data including your private key.

There should be a workaround or a fallback for this case. Luckily I had a backup, but this is a serious issue anyway.

**Comment by greizgh** [comment]
Sorry about that, I forgot that the implementation was not complete until firefox 53.
Saving in both sync and local storage should do the trick for now.

**Comment by greizgh** [comment]
I bumped the firefox constraint to >=53 (which implements sync storage) and disabled v2.2.0.
You should be able to downgrade to v2.1, your ESR version should not auto update the addon.
