### ISSUE TITLE
How does the site length field work?

### ISSUE THREAD

**Issue by pzrq** [greizgh/Phashword#27]
I tried to set length up to say 40 or 50 characters, but I'm only seeing up to 27 characters in the generated `password` field.

Is this a deliberate limitation or a :bug: I should help hunt down if time permits?

Aside: I realised that changing the length is one way one might be able to handle other websites being hacked over time without needing to also rotate one's master password.

**Comment by greizgh** [comment]
Hi,
Phashword does not limit the password length.
Websites however are able to limit the input length of the password field.

You may check the maximum allowed password length by inspecting the page. See 'maxlength' on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
