### ISSUE TITLE
Where exactly is the secret stored?

### ISSUE THREAD

**Issue by pzrq** [greizgh/Phashword#28]
The [README.md](https://github.com/greizgh/Phashword/blob/0916e3edefccb277aba79a8b77d98aede9aaca59/README.md) states:

> 2. a secret (stored in your browser, back it up!)

Where exactly is this stored? Somewhere in the file system perhaps? If so, would I need to quit Firefox in order to back up?

**Comment by greizgh** [comment]
The secret is stored in the internal webextension storage. If you have a backup of your firefox profile, it will be included.
If you want to back just the secret, the best way is to note it down somewhere.

The secret is called "private key" and is accessible through the add-on settings page under tab "Profiles". There is one secret per profile.

I hope this helps, feel free to reopen the issue if you need more information.

**Comment by pzrq** [comment]
Thanks @greizgh 👍 

![screen shot 2018-02-13 at 1 02 38 pm](https://user-images.githubusercontent.com/1217010/36130041-6f551f22-10be-11e8-9fc9-94570bb848b6.png)

**Comment by greizgh** [comment]
Hi,
I'm glad you found it.
However, you should'nt have posted this screenshot: the QR code is a visual representation of the secret key (in order to use it on your phone).
You should consider your private key as compromised.

Le 13 février 2018 03:04:55 GMT+01:00, Peter Schmidt <notifications@github.com> a écrit :
>Thanks @greizgh 👍 
>
>![screen shot 2018-02-13 at 1 02 38
>pm](https://user-images.githubusercontent.com/1217010/36130041-6f551f22-10be-11e8-9fc9-94570bb848b6.png)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/greizgh/Phashword/issues/28#issuecomment-365127478

-- 
Greizgh

**Comment by pzrq** [comment]
@greizgh Thank you! Good thing that particular secret key was not used to generate any passwords 😉
